-- NIFTY AI Trade Learning persistent storage
-- Run this once in Supabase SQL Editor.

create table if not exists public.ai_trade_setups (
  id bigint generated by default as identity primary key,
  timestamp text not null,
  direction text not null check (direction in ('BUY','SELL')),
  strike integer,
  option_type text,
  underlying_entry double precision not null,
  stop_loss double precision not null,
  target double precision not null,
  confidence_pct double precision,
  factors_json text,
  status text not null default 'OPEN' check (status in ('OPEN','WIN','LOSS','EXPIRED')),
  exit_price double precision,
  exit_timestamp text
);

create index if not exists idx_ai_trade_setups_status_id
  on public.ai_trade_setups(status, id desc);

-- The Streamlit app should preferably use the Supabase service-role key
-- as a server-side secret. Do NOT expose that key to the browser/client.
-- If you deliberately use the anon key, configure appropriate RLS policies
-- for your own security model instead of blindly making the table public.
