-- NIFTY AI Trade Learning persistent storage
-- Run this once in Supabase SQL Editor.

create table if not exists public.ai_trade_setups (
  id bigint generated by default as identity primary key,
  timestamp text not null,
  direction text not null check (direction in ('BUY','SELL')),
  strike integer,
  option_type text,
  underlying_entry double precision not null,
  stop_loss double precision not null,
  target double precision not null,
  confidence_pct double precision,
  factors_json text,
  status text not null default 'OPEN' check (status in ('OPEN','WIN','LOSS','EXPIRED')),
  exit_price double precision,
  exit_timestamp text
);

create index if not exists idx_ai_trade_setups_status_id
  on public.ai_trade_setups(status, id desc);

-- The Streamlit app should preferably use the Supabase service-role key
-- as a server-side secret. Do NOT expose that key to the browser/client.
-- If you deliberately use the anon key, configure appropriate RLS policies
-- for your own security model instead of blindly making the table public.

-- Multi-stock additive tables. Existing ai_trade_setups is intentionally preserved.
create table if not exists public.stock_ai_setups (
  id bigint generated by default as identity primary key,
  symbol text not null,
  timestamp text not null,
  direction text not null check (direction in ('BUY','SELL','NO TRADE')),
  entry double precision,
  stop_loss double precision,
  target double precision,
  confidence_pct double precision,
  factors_json text,
  status text not null default 'OPEN' check (status in ('OPEN','WIN','LOSS','EXPIRED')),
  exit_price double precision,
  exit_timestamp text
);
create index if not exists idx_stock_ai_setups_symbol_status_id
  on public.stock_ai_setups(symbol,status,id desc);

create table if not exists public.stock_learning_profiles (
  symbol text primary key,
  profile_json text not null,
  updated_at text not null
);

create table if not exists public.stock_fundamentals_cache (
  symbol text primary key,
  snapshot_json text not null,
  fetched_at text not null
);

create table if not exists public.stock_news_cache (
  symbol text primary key,
  news_json text not null,
  fetched_at text not null
);
