-- Additive Gold/Silver learning + cache tables.
-- Run after the existing Supabase schema/multi-stock migration.
-- Does not drop, truncate, or modify existing trade history.

create table if not exists public.commodity_ai_setups (
  id bigint generated by default as identity primary key,
  asset text not null check (asset in ('GOLD','SILVER')),
  timestamp text not null,
  direction text not null check (direction in ('BUY','SELL','NO TRADE')),
  entry double precision,
  stop_loss double precision,
  target double precision,
  confidence_pct double precision,
  factors_json text,
  status text not null default 'OPEN' check (status in ('OPEN','WIN','LOSS','EXPIRED')),
  exit_price double precision,
  exit_timestamp text,
  mfe double precision,
  mae double precision,
  immediate_reversal boolean,
  created_at timestamptz not null default now()
);
create index if not exists idx_commodity_ai_setups_asset_status_id
  on public.commodity_ai_setups(asset,status,id desc);

create table if not exists public.commodity_learning_profiles (
  asset text primary key,
  profile_json text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.commodity_fundamentals_cache (
  asset text primary key,
  snapshot_json text not null,
  fetched_at timestamptz not null default now()
);

create table if not exists public.commodity_news_cache (
  asset text primary key,
  news_json text not null,
  fetched_at timestamptz not null default now()
);
