-- OPTIONAL / ONE-TIME additive migration for Multi-Stock Intelligence.
-- DO NOT drop, truncate, or recreate ai_trade_setups.
-- Existing SUPABASE_URL / SUPABASE_KEY remain unchanged.

create table if not exists public.stock_ai_setups (
  id bigint generated by default as identity primary key,
  symbol text not null,
  timestamp text not null,
  direction text not null check (direction in ('BUY','SELL','NO TRADE')),
  entry double precision,
  stop_loss double precision,
  target double precision,
  confidence_pct double precision,
  factors_json text,
  status text not null default 'OPEN' check (status in ('OPEN','WIN','LOSS','EXPIRED')),
  exit_price double precision,
  exit_timestamp text
);
create index if not exists idx_stock_ai_setups_symbol_status_id
  on public.stock_ai_setups(symbol,status,id desc);

create table if not exists public.stock_learning_profiles (
  symbol text primary key,
  profile_json text not null,
  updated_at text not null
);

create table if not exists public.stock_fundamentals_cache (
  symbol text primary key,
  snapshot_json text not null,
  fetched_at text not null
);

create table if not exists public.stock_news_cache (
  symbol text primary key,
  news_json text not null,
  fetched_at text not null
);


-- NIFTY 50 aggregate context cache (additive; safe to run repeatedly).
create table if not exists public.nifty50_fundamentals_cache (
  cache_key text primary key,
  snapshot_json text not null,
  fetched_at text not null
);

create table if not exists public.nifty50_news_cache (
  cache_key text primary key,
  news_json text not null,
  fetched_at text not null
);
